### ISSUE TITLE
Document TRS specification's requirement that are not covered by Yevs registry

### ISSUE THREAD

**Issue by inutano** [ddbj/yevis-cli#5]
From https://github.com/ddbj/workflow-registry/issues/15

From @suecharo 
> As stated at https://editor.swagger.io/?url=https://raw.githubusercontent.com/ga4gh/tool-registry-schemas/develop/openapi/openapi.yaml, "Descriptors can often include imports that refer to additional descriptors. This returns additional descriptors for the specified tool in the same or other directories that can be reached as a relative path. This endpoint can be useful for workflow engine implementations like cwltool to programmatically download all the descriptors for a tool and run it. This can optionally include other files described with FileWrappers such as test parameters and containerfiles.", the original TRS definition indeed expects that behavior.
> However, in yevis, due to the specification that returns TRS responses via GitHub pages, we are unable to implement this behavior. Instead, we're including the download link in the path of the /files response.

ToDo:
- Yevis-cli のドキュメントに追記
- Yevis-cli から生成されたレジストリのドキュメントに追記できるか？

**Comment by suecharo** [comment]
Updated document as:
https://github.com/sapporo-wes/yevis-cli#generated-trs-responses

**Comment by inutano** [comment]
Thanks!!
